### PR TITLE
Andrei revision 1

### PR DESCRIPTION
**Pull request by ljubobratovicrelja**
Revision fixup from Andrei's feedback on forums, first pass.
@9il could you please make a double check on these changes? - I'll be unavailable for the most part of the day, so feel free to fix and merge as you'd like.

### CODE REVIEW

**Comment by ljubobratovicrelja** [comment]
I have also removed threshold score from the table. I believe Johan is right, average results are more realistic now, and I think this is the right thing to do.

**Comment by ljubobratovicrelja** [comment]
@9il thank you!

**Comment by 9il** [comment]
You still need to replace `I` with `we`. This is better for any kind of academic like article. Does not matter if you are a single author. Plus you may want to add Andrei to `Acknowledgements`

**Comment by ljubobratovicrelja** [comment]
> You still need to replace I with we. This is better for any kind of academic like article. Does not matter if you are a single author. Plus you may want to add Andrei to Acknowledgements

Will do. I think I can get this done by 2pm UTC.

**Pull request merged**
