### PR TITLE
[post] Transformed density rejection sampling

### PR DESCRIPTION
**Pull request by wilzbach**
This is part two and is still WIP as it requires a proper introduction from part 1 and some style fixes (e.g. images also vertically centered).

### CODE REVIEW

**Comment by wilzbach** [comment]
@WebDrake @joseph-wakeling-sociomantic @9il

I have written two blog posts about `mir.random.flex` and I really hope you like them:

http://blog.mir.dlang.io/random/2016/08/19/intro-to-random-sampling.html
http://blog.mir.dlang.io/random/2016/08/22/transformed-density-rejection-sampling.html

I plan to make the release announcement **today**, so in case you find anything major in these two posts let me know ASAP :)

(FYI: In lack of a preview blog and as the blog hasn't been officially announced anywhere, I have already uploaded the posts despite the open status of this PR)

**Comment by joseph-wakeling-sociomantic** [comment]
Blog posts look great to me :-)

One thought -- you might want to include (for context) a reference to Hörmann's 1995 paper "A rejection technique for sampling from T-concave distributions", which introduces the basic concept that Tinflex derives from.  I would also make sure to explicitly give the full citation of all papers you reference in your blog posts, not just links.

**Comment by wilzbach** [comment]
> Blog posts look great to me :-)

Glad to hear that :)

> One thought -- you might want to include (for context) a reference to Hörmann's 1995 paper "A rejection technique for sampling from T-concave distributions", which introduces the basic concept that Tinflex derives from.

There's also a paper from 2003 and a book which explain the basic concepts too.

> I would also make sure to explicitly give the full citation of all papers you reference in your blog posts, not just links.

Thanks for the good idea! I hope I got all of them:

http://blog.mir.dlang.io/random/2016/08/19/intro-to-random-sampling.html#literature-references
http://blog.mir.dlang.io/random/2016/08/22/transformed-density-rejection-sampling.html#literature-references

While there still might be typos or small glitches left, I will go ahead and merge this as such small fixes can be follow-up PRs and I think the content overall is in a good shape.

**Comment by joseph-wakeling-sociomantic** [comment]
> Thanks for the good idea! I hope I got all of them:

I'd put them in author-year order, but not a big deal ;-)

**Comment by wilzbach** [comment]
> I'd put them in author-year order, but not a big deal ;-)

Due to my bad personal taste I did the inverse and ordered them chronically because no tokens (like in a usual paper) are used and I wanted to give the reader the opportunity to see the development over time (in this case newer papers nearly always include improvements) ;-)

**Comment by joseph-wakeling-sociomantic** [comment]
Yea, I thought that might be the reason for your choice.  Fine by me :-)

**Comment by joseph-wakeling-sociomantic** [comment]
One other thought about your 1st blog post: the graphic where you show the acceptance and rejection of points (in the section "The Rejection Method") is great, but one thing it doesn't make clear is the behaviour of the squeeze function (which is not discussed until a later section).  I wonder if you could maybe do something with colour to highlight the points accepted because of the squeeze function, versus the points in-between squeeze and f(x), versus the rejected points ... ?

**Comment by joseph-wakeling-sociomantic** [comment]
One thing which I should have picked up on already: "Non-uniform random sampling" is maybe misleading terminology.  "Sampling from non-uniform random distributions" is a more exact choice of words ("non-uniform random sampling" is probably more appropriately applied to things like choosing a subset of items where the probability of picking individual items is not uniformly distributed).

**Comment by wilzbach** [comment]
> One thing which I should have picked up on already: "Non-uniform random sampling" is maybe misleading terminology. "Sampling from non-uniform random distributions" is a more exact choice of words ("non-uniform random sampling" is probably more appropriately applied to things like choosing a subset of items where the probability of picking individual items is not uniformly distributed).

Argh .. thanks for pointing this out and correcting in the NG! For [Reddit](http://blog.mir.dlang.io/random/2016/08/19/intro-to-random-sampling.html) and [Twitter](https://twitter.com/D_Programming/status/767948342865244160) it was unfortunately too late, but it seems that nobody cared ;-)

The title of the blog post is of course corrected and I will pay more care in the future! :)

**Comment by WebDrake** [comment]
No, any fault's entirely mine.  I didn't raise the issue early enough!

The bottom line of all of this is that you've done a great piece of work which you should be really, really proud of -- congratulations on a very productive project! :-)

**Pull request merged**
